version: '3'
services:

  # MariaDB
  mariadb:
    image: mariadb/server:10.4
    environment:
      #MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: default_database
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    #volumes:
    #  - ./storage:/var/lib/mysql
    #  - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8085:8080"
    depends_on:
      - mariadb

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: localhost
    depends_on:
      - adminer

  kafka:
    image: wurstmeister/kafka
    command: [ start-kafka.sh ]
    ports:
      - "9092:9092"
    hostname: 127.0.0.1
    environment:
      KAFKA_CREATE_TOPICS: "test-topic-read:1:1,test-topic-write:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper