management:
  info:
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  application:
    name: kisonar-poc-spring-security
    main:
      banner-mode: "on"
    http.encoding:
      charset: UTF-8
      enabled: true
      force: true



jwt:
  secret: javainuse