name: 'Kisonar POC GHA check'

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check identity
        run: whoami
