name: 'Kisonar POC CI'

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: GitHub checkout action
        uses: actions/checkout@v3
      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19.0.1+10'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Print Gradle version
        run: gradle --version
      - name: Execute Gradle build
        run: gradle clean build